import os
import json
from fastapi import APIRouter, HTTPException

router = APIRouter(tags=["Postcall Data API"])

# Reference to the .txt file generated by the postcall agent
DB_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'postcall', 'result.txt')

def get_db_data():
    """Helper to read the mock database file."""
    if not os.path.exists(DB_FILE):
        return []
    with open(DB_FILE, 'r') as f:
        try:
            return json.load(f)
        except:
            return []

# 1. API used to fetch the Conversation Transcript for the text box
@router.get("/api/users/{case_id}/transcript")
def get_transcript(case_id: str):
    data = get_db_data()
    for user in data:
        if user.get("case_id") == case_id:
            return {"transcript": user.get("transcript", "")}
    raise HTTPException(status_code=404, detail="User not found")

# 2. API used to fetch the generated Summary for the summary text box
@router.get("/api/users/{case_id}/summary")
def get_summary(case_id: str):
    data = get_db_data()
    for user in data:
        if user.get("case_id") == case_id:
            return {"summary": user.get("summary", "")}
    raise HTTPException(status_code=404, detail="User not found")

# 3. API used to fetch the extracted Action Items for the action items text box
@router.get("/api/users/{case_id}/action_items")
def get_action_items(case_id: str):
    data = get_db_data()
    for user in data:
        if user.get("case_id") == case_id:
            return {"action_items": user.get("action_items", [])}
    raise HTTPException(status_code=404, detail="User not found")

# 4. API used to fetch the Final Categorization for the categorization text box
@router.get("/api/users/{case_id}/categorization")
def get_categorization(case_id: str):
    data = get_db_data()
    for user in data:
        if user.get("case_id") == case_id:
            return {"categorization": user.get("categorization", "")}
    raise HTTPException(status_code=404, detail="User not found")


