import os
import json
from dotenv import load_dotenv
from langchain_openai import AzureChatOpenAI
from langchain.agents import initialize_agent, AgentType
from langchain.tools import tool
from azure.cosmos import CosmosClient

load_dotenv()

# ---------------------------------------------------------
# 1. DEFINE LANGCHAIN TOOLS
# ---------------------------------------------------------

@tool
def summarize_transcript(transcript: str) -> str:
    """Useful for summarizing a conversation transcript into a short paragraph."""
    # In a real scenario, you can chain this to another LLM call or just instruct the agent to do it.
    # The agent uses this tool to format/generate the summary.
    return "This is a placeholder summary generated by the LLM from the transcript."

@tool
def categorize_call(transcript: str) -> str:
    """Useful for categorizing the call (e.g., 'Promise to Pay', 'Dispute', 'Not Interested')."""
    return "Promise to Pay"

@tool
def extract_action_items(transcript: str) -> str:
    """Useful for extracting action items for both the user and the agent. Returns a JSON string."""
    action_items = {
        "user_action": "User agreed to pay by Friday.",
        "agent_action_item": "Agent needs to send an email reminder on Thursday."
    }
    return json.dumps(action_items)

@tool
def write_back_to_cosmosdb(call_sid: str, summary: str, category: str, action_items_json: str) -> str:
    """
    Useful for taking the final summary, category, and action items and writing them
    back directly into the Azure Cosmos DB container for the specified call_sid.
    """
    endpoint = os.getenv("ENDPOINT")
    key = os.getenv("KEY")
    database_name = os.getenv("DATABASE_NAME", "user-data")
    container_name = os.getenv("CONTAINER_NAME", "user-statements")

    if not endpoint or not key:
        return "Error: Cosmos DB credentials missing."

    try:
        client = CosmosClient(endpoint, credential=key)
        db = client.get_database_client(database_name)
        container = db.get_container_client(container_name)
        
        # 1. Read the existing document
        item = container.read_item(item=call_sid, partition_key=call_sid)
        
        # 2. Append the new data
        # Ensure notes and status exist as lists
        if "notes" not in item or not isinstance(item["notes"], list):
            item["notes"] = []
        if "status" not in item or not isinstance(item["status"], list):
            item["status"] = []
            
        item["notes"].append(summary)
        item["status"].append(category)
        item["action_items"] = json.loads(action_items_json)
        
        # 3. Upsert back to the database
        container.upsert_item(item)
        return "Successfully updated Cosmos DB with summary, category, and action items."
    except Exception as e:
        return f"Database update failed: {str(e)}"

# ---------------------------------------------------------
# 2. INITIALIZE AGENT
# ---------------------------------------------------------

def run_postcall_agent(call_sid: str, transcript: list):
    """
    Main function to execute the LangChain Post-Call agent.
    """
    # Use Azure OpenAI (matching your existing configuration)
    llm = AzureChatOpenAI(
        azure_deployment=os.getenv("AZURE_DEPLOYMENT"),
        openai_api_version=os.getenv("AZURE_API_VERSION"),
        azure_endpoint=os.getenv("AZURE_ENDPOINT"),
        api_key=os.getenv("AZURE_API_KEY"),
        temperature=0
    )

    tools = [
        summarize_transcript,
        categorize_call,
        extract_action_items,
        write_back_to_cosmosdb
    ]

    agent = initialize_agent(
        tools=tools,
        llm=llm,
        agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
        verbose=True
    )
    
    # Format the transcript into a readable string
    transcript_str = "\\n".join([f"{msg.get('role', 'unknown')}: {msg.get('content', '')}" for msg in transcript])

    prompt = f"""
    You are a Post-Call Analysis AI. You have been given the transcript for Call SID '{call_sid}'.
    
    TRANSCRIPT:
    {transcript_str}
    
    INSTRUCTIONS:
    1. Use tools to summarize the transcript, categorize the call, and extract action items.
    2. Once you have those three pieces of information, use the 'write_back_to_cosmosdb' tool 
       to save them to the database using the Call SID: {call_sid}.
    3. Return a successful completion message.
    """
    
    response = agent.run(prompt)
    print("Post-Call Agent Finished:", response)
    return response

if __name__ == "__main__":
    # Example local runner
    sample_transcript = [{"role": "user", "content": "I will pay tomorrow."}]
    run_postcall_agent("CA_FAKE_TRIAL_123", sample_transcript)
